# <u> Les t-uplets </u>

  <font color='green'> Bonjour a tous,
Nous avons vu, dans le Thème B: Types construits, les chaines de caractères, les listes et les matrices.
Dans ce cours, nous allons découvrir un autre type construit, Les t-uplets.
Je vous invite a lire le cours étape par étape et surtout ne pas sauter les paragraphes.

Il est nécessaire de faire tous les exemples et de comprendre en profondeur ce qu'il se passe quand vous exécuter les exemples.

En Python, un tuple est une séquence d'éléments de type quelconque, séparés par des virgules.
Le tout est « encapsulé » dans des parenthèses (contrairement aux listes qui utilisent les crochets).

Executer les lignes suivantes, vous remarquerez que a et b sont tous les deux de type 'tuple'

In [1]:
# Exemple 1
a = (2, 3)

print (type(a))

b = ("coucou", "bonjour")

print (type(b))

<class 'tuple'>
<class 'tuple'>

 <u><font color='green'> Vocabulaire </font> </u>

Le mot anglais « tuple » se traduit en français par multiplet, ou encore par t-uplet.
On parle aussi de n-uplet pour désigner des t-uplets de longueur n.

Vous avez déjà manipulé cette notion (en mathématiques) : le couple ( x, y)
des coordonnées d'un point dans un repère est un 2-uplet.

* Un 1-uplet est aussi appelé simplet.
* Un 2-uplet est aussi appelé couple.
* Un 3-uplet est aussi appelé triplet.
* Un 4-uplet est aussi appelé quadruplet.
* On peut poursuivre avec les quintuplets, sextuplets, etc...

## <u> T-uplet en Python </u>

Un t-uplet est une séquence <font color='green'>immuable </font> d'éléments. On retrouve avec les objets de type tuple une grande partie des propriétés communes aux séquences d'éléments en Python (chaînes et tableaux).

### <u>1. Définir un tuple directement</u>
On définit un tuple de façon directe en écrivant son contenu entre parenthèses. Executer les exemples suivants et remarquez surtout la difference entre  a = (2,)  et b= (2)

In [3]:
#Exemple 2
a = (2, 3, 4)
# ou
a= 2, 3, 4
print (b)

#Cas particuliers:

# 1. Pour définir un tuple vide, on peut uniquement affecter un couple de parenthèses :
a = ()
print (type(a))

# 2. Pour éviter les confusions, il est aussi possible de forcer le typage grâce à la fonction tuple() :
a = tuple()
print (type(a))

# 3. Pour définir un tuple ne contenant qu'un seul élément (simplet), il faut faire suivre cet élément par une virgule dans les parenthèses :
a = (2,)
b= (2)
print (type(a), type (b))

('coucou', 'bonjour')
<class 'tuple'>
<class 'tuple'>
<class 'tuple'> <class 'int'>

### <u> 2. Définir un tuple par comprehension </u>
On peut aussi définir un T-uplet par compréhension. C'est la meme syntaxe utilisée dans les tableaux a une différence près:
* Il faut encapsuler la définition entre parenthèses.
* Faire précéder la parenthèse par le mot clé tuple

Exécuter l'exemple suivant :

In [4]:
#Exemple 3 :
# creer par comprehension un t-uplet  qui contient les entier de -40 a 40 inclus.
t= tuple(i for i in range (-40,41))
print (t)

#creer par comprehension un t-uplet qui contient tous les nombres pairs  entre 0 et 100, divisibles par 3.
t2= tuple (i for i in range(0,101)  if i%2==0 and i%3==0)
print(t2)

(-40, -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40)
(0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96)

### <u> 3. Nombre d'éléments et indice des éléments </u>
Comme pour les listes, le nombre des éléments est obtenu avec  la fonction len().<br>
Le principe des indices est le même que ce qui a été vu dans les listes.

Exécuter l'exemple suivant et faites des conclusions :

In [5]:
#Exemple 4
a = (2, 4, 8, 16, 32, 64)  #Soit a un tuple

print(a[5])
print(len(a))
print(a[len(a)-1])
print(a[len(a)]) # Ici, on demande d'afficher l'element a l'indice 6 ce qui va provoquer
                  #une erreur car cela depasse le dernier indice qui est de 5.

64
6
64

IndexError: tuple index out of range

### <u>4. Immuabilite</u>
Comme les chaînes de caractères, un t-uplet est immuable : une fois qu’il est défini, il n’est plus possible de le modifier.<br>
Exemple:
Essayons de redéfinir l'élément d'indice 2 par une affectation :

In [6]:
#Exemple 5
a = (2, 3, 4)
a[2] = 42

TypeError: 'tuple' object does not support item assignment

### <u>5. Concaténation</u>
On peut construire un nouveau t-uplet par concaténation (ajouter bout à bout) de t-uplets déjà définis en utilisant l'opérateur d'addition « + ». Essayer l'exemple suivant:

In [8]:
#Exemple 6
a = ("bonjour", "tout")

b = ("le", "monde")

c = a + b

print ('la valeur de c est :', c)

d=(2,)

d= d * 4 # comme dans le cas des chaines de caracteres et des listes on peut utiliser l'operateur * pour
         # concatener la meme valeur plusieurs fois (ici c'est 4)
print ('la valeur de d est :', d)

la valeur de c est : ('bonjour', 'tout', 'le', 'monde')
la valeur de d est : (2, 2, 2, 2)

<font  color= 'red' > Comme avec les chaînes de caractères, l'affectation d'une expression concaténée permet de construire un nouvel objet de type tuple. </font>

In [9]:
# Exemple 7
# On ne peut pas ajouter des éléments à un tuple comme pour un tableau avec la méthode append
a=(3,4,6,7,-8,10)
a.append(45)
print (a)

AttributeError: 'tuple' object has no attribute 'append'

### <u>  6. Parcourir les éléments d'un t-uplet </u>
comme pour les chaine de caracteres et les listes, il existe trois méthodes pour parcourir les valeurs d'un t-uplet.

- On peut parcourir élément par élément d'un t-uplet avec for ... in ...:
- On peut parcourir le t-uplet indice par indice grâce à for ... in range(len(...)):
- On peut aussi parcourir le t-uplet en utilisant à la fois les indices et les valeurs des éléments grâce à for ... in enumerate(...):

### Exemples:

In [10]:
# Exemple  8: Parcourir un tuple:
a=(3,4,6,7,-8,10)
for element in a:
    print (element)

for i in range(len(a)):
    print (a[i])

for index, valeur  in enumerate(a):
    print(index, valeur)

3
4
6
7
-8
10
3
4
6
7
-8
10
0 3
1 4
2 6
3 7
4 -8
5 10

In [13]:
# Exemple 9 : faire cet exemple.
# on construit les tuples par concatenation comme les chaines de caracteres.
'''
Complétez la définition de la fonction signes() qui prend pour paramètre un t-uplet t
contenant des eniers et renvoie un t-uplet de même longueur contenant un 0 lorsque l'élément
correspondant de t est strictement positif, un 1 sinon.
'''
def signes(t):

    """
    t – tuple, t-uplet d’entiers
    Sortie: tuple – t-uplet de même longueur que t contenant :
            0 si l’élément de même rang dans t est strictement positif
            1 si l’élément de même rang dans t est négatif
    >>> signes( (3, -2, -6, 0) )
    (0, 1, 1, 1)
    """
    t2=tuple()
    for element in t:
        if element>0:
            t2=t2+(0,)
        else:
            t2=t2+(1,)
    return t2

print(signes((4,-2,-1,25,-14,2,24,-2)))

(0, 1, 1, 0, 1, 0, 0, 1)

In [18]:
# Suite Exemple 9
# #Donnez la définition par compréhension d'un t-uplet qui génère 10 entiers aléatoires compris entre -50 et 50
# (après avoir importé la module random).
import random
t=tuple(random.randint(-50,50) for i in range(10))
print(t)

(-6, -49, 43, -14, -13, 37, 18, -48, -50, 2)

In [21]:
# Suite Exemple 9
# #Regroupez les deux questions dans un unique programme afin de tester la fonction signes()
# dans le « main » à l'aide de t-uplets générés aléatoirement (cf. Deuxieme partie de l'exemple 1).

#AIDE:
def signes(t):

    '''ici vous devez mettre
    ce que vous avez ecrit plus haut
    '''
    t2=tuple()
    for element in t:
        if element>0:
            t2=t2+(0,)
        else:
            t2=t2+(1,)
    return t2

t=tuple(random.randint(-50,50) for i in range(10))                             #Creation du tuple aleatoirement par comprehension

print(signes(t))

(0, 0, 0, 1, 0, 1, 0, 0, 0, 0)

J'attire votre attention sur le code qui suit:
Il faut comprendre la structure et essayer de la reproduire tout seul.

In [22]:
#Suite  Exemple 9 et fin:
# On peut creer par comprehension le tuple resultat de la fonction signe pour un tuple genere aleatoiremement
from random import *
t= tuple( int (element<=0) for element in tuple(randint(-50,50) for i in range(10)) )
print (t)

(0, 0, 1, 0, 1, 0, 1, 1, 1, 0)

### <u>7.  Déballage des éléments</u>
Un t-uplet permet d’affecter plusieurs variables en une seule fois. Executer ces exemples

In [23]:
# Exemple 10
a, b, c, d = (42, 666, 1789, 1968)
print (a)
print (b)
print (c)
print (d)

#On aurait pu écrire de façon équivalente :
(a, b, c, d) = (42, 666, 1789, 1968)
#ou encore:
a, b, c, d = 42, 666, 1789, 1968

42
666
1789
1968

In [24]:
# Exemple 11: essayer le script suivant:
t = (3, 4, 5, 6)
a, b, c, d = t  # ecrire un commentaire ici pour decrire ce que fait cette instruction
print (a)
#la variable a est affecter a l'indice 0 du tuple t est donc il renvoie 3 car 3 est sur l'indice 0 de t

3

### <u> 9.  Test d'appartenance, comparaison </u>
On peut tester l'appartenance d'un élément à un tuple avec l'opérateur <font  color= 'red' >in </font> et comparer deux tuples avec ==. La comparaison de deux tuples s'effectue de gauche à droite

In [25]:
# Exemple 12
b = (3,4,6,89,30,92)
c = (3,4,6,89,30,92)

# essayer l'instruction suivante:
print (3 in b) # cela devrait nous donner True, car 3 est dans le tuple b
print (110 in b ) # cela devrait nous donner False, car 101 n'est pas dans le tuple b
print (100 not in b) # cela devrait nous donner True
print (b==c) # oui cela est vrai
# par contre :
print(id(b)==id(c)) # nous donnera une valeur False.

True
False
True
True
False

### <u> 10.  Recherche d'elements dans un tuple </u>
 Comme dans les listes, on peut rechercher l'index de la première occurence d'un élément dans un tuple avec la méthode index, ou compter le nombre d'occurences d'une valeur avec count.

In [30]:
#Exemple 13: executer ces lignes de codes
from random import randint
e = tuple([randint(1,6) for _ in range(10)])
print (e.index(5)) # cette instruction donne l'indice de la valeur 5 si 5 est dans e
print (e.index(1)) # cette instruction donne l'indice de la valeur 1 si 1 est dans e

1
0